CREATE VIEW hmda_funnel.v_dashboard_agg AS
SELECT
  state_code, derived_race, derived_ethnicity, derived_sex, applicant_age,
  derived_loan_product_type, funnel_stage, leakage_category, denial_reason_label,
  is_approved_not_converted,
  CASE WHEN income IS NULL THEN 'Unknown' WHEN income < 0 THEN 'Negativo (revisar dato)' WHEN income = 0 THEN 'Cero (revisar dato)' WHEN income < 76 THEN 'Bajo (<$76K)' WHEN income < 146 THEN 'Medio ($76K-$146K)' ELSE 'Alto ($146K+)' END AS income_band,
  CASE WHEN loan_amount < 205000 THEN 'Bajo (<$205K)' WHEN loan_amount < 405000 THEN 'Medio ($205K-$405K)' ELSE 'Alto ($405K+)' END AS loan_amount_band,
  CASE WHEN property_value_num IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN property_value_num < 265000 THEN 'Bajo (<$265K)' WHEN property_value_num < 485000 THEN 'Medio ($265K-$485K)' ELSE 'Alto ($485K+)' END AS property_value_band,
  CASE WHEN ltv_calculated IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN ltv_calculated < 0.797 THEN 'Bajo (<79.7%)' WHEN ltv_calculated < 0.943 THEN 'Medio (79.7%-94.3%)' ELSE 'Alto (94.3%+)' END AS ltv_band,
  CASE WHEN rate_spread_num IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN rate_spread_num < 0 THEN 'Mejor que el mercado (<0)' WHEN rate_spread_num < 1.29 THEN 'Normal (0 a 1.29)' ELSE 'Elevado (>1.29) - mayor abandono' END AS rate_spread_band,
  CASE WHEN debt_to_income_ratio IS NULL OR debt_to_income_ratio IN ('NA', 'Exempt') THEN 'Unknown' WHEN debt_to_income_ratio = '<20%' OR debt_to_income_ratio = '20%-<30%' THEN 'Bajo (<30%)' WHEN debt_to_income_ratio = '30%-<36%' OR TRY_CAST(debt_to_income_ratio AS DOUBLE) BETWEEN 30 AND 49 THEN 'Medio (30%-50%)' ELSE 'Alto (50%+)' END AS dti_band,
  CASE WHEN ffiec_msa_md_median_family_income IS NULL THEN 'Unknown' WHEN ffiec_msa_md_median_family_income = 0 THEN 'Sin dato de área' WHEN ffiec_msa_md_median_family_income < 96785 THEN 'Bajo' WHEN ffiec_msa_md_median_family_income < 124961 THEN 'Medio' ELSE 'Alto' END AS area_median_income_band,
  COUNT(*) AS n_aplicaciones,
  SUM(loan_amount) AS total_loan_amount,
  SUM(CASE WHEN income > 0 THEN income END) AS total_income,
  COUNT(CASE WHEN income > 0 THEN income END) AS n_con_income,
  SUM(rate_spread_num) AS total_rate_spread,
  COUNT(rate_spread_num) AS n_con_rate_spread,
  SUM(origination_charges_num) AS total_origination_charges,
  COUNT(origination_charges_num) AS n_con_origination_charges,
  SUM(interest_rate_num) AS total_interest_rate,
  COUNT(interest_rate_num) AS n_con_interest_rate,
  SUM(total_loan_costs_num) AS total_loan_costs_sum,
  COUNT(total_loan_costs_num) AS n_con_total_loan_costs,
  SUM(discount_points_num) AS total_discount_points,
  COUNT(discount_points_num) AS n_con_discount_points,
  SUM(property_value_num) AS total_property_value,
  COUNT(property_value_num) AS n_con_property_value
FROM hmda_funnel.v_applications_semantic
GROUP BY state_code, derived_race, derived_ethnicity, derived_sex, applicant_age, derived_loan_product_type, funnel_stage, leakage_category, denial_reason_label, is_approved_not_converted,
  CASE WHEN income IS NULL THEN 'Unknown' WHEN income < 0 THEN 'Negativo (revisar dato)' WHEN income = 0 THEN 'Cero (revisar dato)' WHEN income < 76 THEN 'Bajo (<$76K)' WHEN income < 146 THEN 'Medio ($76K-$146K)' ELSE 'Alto ($146K+)' END,
  CASE WHEN loan_amount < 205000 THEN 'Bajo (<$205K)' WHEN loan_amount < 405000 THEN 'Medio ($205K-$405K)' ELSE 'Alto ($405K+)' END,
  CASE WHEN property_value_num IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN property_value_num < 265000 THEN 'Bajo (<$265K)' WHEN property_value_num < 485000 THEN 'Medio ($265K-$485K)' ELSE 'Alto ($485K+)' END,
  CASE WHEN ltv_calculated IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN ltv_calculated < 0.797 THEN 'Bajo (<79.7%)' WHEN ltv_calculated < 0.943 THEN 'Medio (79.7%-94.3%)' ELSE 'Alto (94.3%+)' END,
  CASE WHEN rate_spread_num IS NULL THEN 'Unknown (Withdrawn/Incomplete)' WHEN rate_spread_num < 0 THEN 'Mejor que el mercado (<0)' WHEN rate_spread_num < 1.29 THEN 'Normal (0 a 1.29)' ELSE 'Elevado (>1.29) - mayor abandono' END,
  CASE WHEN debt_to_income_ratio IS NULL OR debt_to_income_ratio IN ('NA', 'Exempt') THEN 'Unknown' WHEN debt_to_income_ratio = '<20%' OR debt_to_income_ratio = '20%-<30%' THEN 'Bajo (<30%)' WHEN debt_to_income_ratio = '30%-<36%' OR TRY_CAST(debt_to_income_ratio AS DOUBLE) BETWEEN 30 AND 49 THEN 'Medio (30%-50%)' ELSE 'Alto (50%+)' END,
  CASE WHEN ffiec_msa_md_median_family_income IS NULL THEN 'Unknown' WHEN ffiec_msa_md_median_family_income = 0 THEN 'Sin dato de área' WHEN ffiec_msa_md_median_family_income < 96785 THEN 'Bajo' WHEN ffiec_msa_md_median_family_income < 124961 THEN 'Medio' ELSE 'Alto' END;
